# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: baseWebApp
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZWEzNzMzMWEyZTA2NDRiNzMzNDU4MWMxZmNiZjdiZjhmNDJiYTlmNDgwNjgxZjVmMmE0Yzk3ZDM0MDU2YjgwYTgyZmZhYzgzODBhOTY4NDBhNDc1OTA0MTk3Mzg1MjFmMzUyZTIxMDZkMzNjMTAyNjE5MmY5ZDdjMWJjOWY2ZWQ=
